apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.0.4/manifests/ha/install.yaml
- service.yaml
#- github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.3.3

#patches:
#  - patches/argocd-server-deployment.yaml

#replicas:
#  - name: argocd-dex-server
#    count: 0

commonAnnotations:
  argocd/version: v2.0.4
  environment: temporary
